// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyqujqezwbgxeqvmgmff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5cXVqcWV6d2JneGVxdm1nbWZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMTUxMzUsImV4cCI6MjA2Nzg5MTEzNX0.O8u8UE9XBnwnQxT2ipfB6GqMH0uGuAQrf43L-vnJn4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});